# -*- coding: utf-8 -*-
"""Deep Q_learning.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xIZKSyb-BJpJsgSRWr6So_rlRlKWCFvK

Installing gynasium
"""

!pip install gymnasium
!pip install "gymnasium[atari, accept-rom-license]"
!apt-get install -y swig
!pip install gymnasium[box2d]

"""Importing the Libraries"""

import os
import random
import numpy as np
import torch
import torch.nn as nn
import torch.optim as optim
import torch.nn.functional as F
import torch.autograd as autograd
from torch.autograd import Variable
from collections import deque, namedtuple

"""Creating the architecture of the Neural Network"""

class NN(nn.Module):
  def __init__(self, state_size, action_size, seed = 42):
    super(NN, self).__init__()
    self.seed = torch.manual_seed(seed)
    self.fully_connected_layer_1 = nn.Linear(state_size,64)
    self.fully_connected_layer_2 = nn.Linear(64,64)
    self.fully_connected_layer_3 = nn.Linear(64,action_size)

  def forward(self,state):
    x = self.fully_connected_layer_1(state)
    x = F.relu(x)
    x = self.fully_connected_layer_2(x)
    x = F.relu(x)
    return self.fully_connected_layer_3(x)

"""**Training the AI**

Setting up the Env
"""

import gymnasium as gym
env = gym.make("LunarLander-v2")
state_shape = env.observation_space.shape
print("state shape =",state_shape)
state_size = env.observation_space.shape[0]
print("state size =",state_size)
num_actions = env.action_space.n
print("number actions =",num_actions)

"""Initializing the Hyperparameters"""

learning_rate = 5e-4
minibatch_size = 100
discount_factor = 0.98
replay_buffer_size = int(1e5)
interpolation_parameter = 1e-3

"""Implementing Experience replay"""

class replay_Memory(object):

  def __init__(self,capacity):
    self.device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
    self.capacity = capacity
    self.memory = []

  def push(self,event):
    self.memory.append(event)
    if(len(self.memory) > self.capacity):
      del self.memory[0]                                                        # deletes the first element from the list

  def sample(self, batch_size):                                                 # randomly selects batch of experiences
    experiences = random.sample(self.memory, k = batch_size)
    states = torch.from_numpy(np.vstack([e[0] for e in experiences if e is not None])).float().to(self.device)                # making tensors form the stacked list
    actions = torch.from_numpy(np.vstack([e[1] for e in experiences if e is not None])).long().to(self.device)
    rewards = torch.from_numpy(np.vstack([e[2] for e in experiences if e is not None])).float().to(self.device)
    next_states = torch.from_numpy(np.vstack([e[3] for e in experiences if e is not None])).float().to(self.device)
    dones = torch.from_numpy(np.vstack([e[4] for e in experiences if e is not None]).astype(np.uint8)).float().to(self.device)
    return states, next_states, actions, rewards, dones

"""Implementing the DQN class"""

class Agent():

  def __init__(self,state_size, action_size):
    self.device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
    self.state_size = state_size
    self.action_size = action_size
    self.local_QNewtork = NN(state_size,action_size).to(self.device)
    self.target_QNetwork = NN(state_size, action_size).to(self.device)
    self.optimizer = optim.Adam(self.local_QNewtork.parameters(), lr = learning_rate)
    self.memory = replay_Memory(replay_buffer_size)
    self.time_step = 0

  def step(self,state,action,reward,next_state,done):
    self.memory.push((state,action,reward,next_state,done))
    self.time_step = (self.time_step+1) % 4
    if self.time_step == 0:
      if(len(self.memory.memory) > minibatch_size):
        experiences = self.memory.sample(100)
        self.learn(experiences,discount_factor)

  def act(self,state,epsilon= 0.):
    state = torch.from_numpy(state).float().unsqueeze(0).to(self.device)
    self.local_QNewtork.eval()
    with torch.no_grad():
      action_values = self.local_QNewtork(state)
    self.local_QNewtork.train()
    if random.random() > epsilon:
      return np.argmax(action_values.cpu().data.numpy())
    else:
      return random.choice(np.arange(self.action_size))

  def learn(self,experiences,discount_factor):
    states,next_states,actions,rewards,dones = experiences
    next_q_targets = self.target_QNetwork(next_states).detach().max(1)[0].unsqueeze(1)      #it gives 2 tensors one the value and the second is it index
    q_targets = rewards + (discount_factor * next_q_targets * (1-dones))
    q_expected = self.local_QNewtork(states).gather(1, actions)
    loss = F.mse_loss(q_expected,q_targets)
    self.optimizer.zero_grad()
    loss.backward()
    self.optimizer.step()
    self.soft_update(self.local_QNewtork, self.target_QNetwork, interpolation_parameter)

  def soft_update(self,local_model,target_model,interpolation_parameter):
    for target_parameter,local_parameter in zip(target_model.parameters(),local_model.parameters()):
      target_parameter.data.copy_(interpolation_parameter * local_parameter.data + (1.0-interpolation_parameter)*target_parameter.data)

"""Initialize The DQN Agent

"""

agent = Agent(state_size,num_actions)

"""Training the DQN agent"""

num_episodes = 2000
max_num_time_steps = 1000
epsilon_start_value = 1.0
epsilon_end_value =0.01
epsilon_decay_value = 0.995
epsilon = epsilon_start_value
scores_on_100_episodes = deque(maxlen=100)

for episode in range(1, num_episodes+1):
  state, _ = env.reset()
  score = 0
  for time_steps in range(max_num_time_steps):
    action = agent.act(state, epsilon)
    next_state , reward, done, _, _ = env.step(action)
    agent.step(state,action, reward,next_state,done)
    state = next_state
    score += reward
    if done:
      break
  scores_on_100_episodes.append(score)
  epsilon = max(epsilon_end_value, epsilon_decay_value*epsilon)
  print('\rEpisode{}\tAverage Score: {:.2f}'.format(episode, np.mean(scores_on_100_episodes)),end = "")
  if episode % 100 ==0:
    print('\rEpisode{}\tAverage Score: {:.2f}'.format(episode, np.mean(scores_on_100_episodes)))
  if np.mean(scores_on_100_episodes) >= 200.0:
    print('\rEnvironment solved in {:d}\tAverage Score: {:.2f}'.format(episode - 100, np.mean(scores_on_100_episodes)))
    torch.save(agent.local_QNewtork.state_dict(),'checkpoint.pth')
    break

"""Visulaizing the results"""

import glob
import io
import base64
import imageio
from IPython.display import HTML, display
from gym.wrappers.monitoring.video_recorder import VideoRecorder

def show_video_of_model(agent, env_name):
    env = gym.make(env_name, render_mode='rgb_array')
    state, _ = env.reset()
    done = False
    frames = []
    while not done:
        frame = env.render()
        frames.append(frame)
        action = agent.act(state)
        state, reward, done, _, _ = env.step(action.item())
    env.close()
    imageio.mimsave('video.mp4', frames, fps=30)

show_video_of_model(agent, 'LunarLander-v2')

def show_video():
    mp4list = glob.glob('*.mp4')
    if len(mp4list) > 0:
        mp4 = mp4list[0]
        video = io.open(mp4, 'r+b').read()
        encoded = base64.b64encode(video)
        display(HTML(data='''<video alt="test" autoplay
                loop controls style="height: 400px;">
                <source src="data:video/mp4;base64,{0}" type="video/mp4" />
             </video>'''.format(encoded.decode('ascii'))))
    else:
        print("Could not find video")

show_video()